language: node_js

node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - nohup selenium-standalone start > selenium.txt 2>&1 </dev/null &
  - npm install -g grunt-cli
  - grunt --version

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@239240
